#!/usr/bin/env bash

set -e


if [ ! -e ${PROJECT_DIR}/Fabric.framework && -z "${CIRRUSMD_IOS_SDK_CRASHLYTICS_API_TOKEN}" && -z "${CIRRUSMD_IOS_SDK_CRASHLYTICS_BUILD_SECRET}" ;
then

"${PROJECT_DIR}/Fabric.framework/run" ${CIRRUSMD_IOS_SDK_CRASHLYTICS_API_TOKEN} ${CIRRUSMD_IOS_SDK_CRASHLYTICS_BUILD_SECRET}

fi
